// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"database/sql"
)

type Role struct {
	ID   int32
	Role sql.NullString
}

type User struct {
	ID       int32
	Name     sql.NullString
	Username sql.NullString
	Password sql.NullString
}

type UsersRole struct {
	ID     int32
	UserID int32
	RoleID int32
}
