// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteUser(ctx context.Context, id int32) error
	GetAllUsers(ctx context.Context) ([]User, error)
	GetUserById(ctx context.Context, id int32) (User, error)
	TestSelectGender(ctx context.Context) ([]sql.NullString, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
}

var _ Querier = (*Queries)(nil)
